/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/wangquan/Documents/学习/vue案例/my-vue-doc/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f147a2d4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f147a2d4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3d5ab436",
    path: "/guide/notes/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d5ab436").then(next)
    },
  },
  {
    name: "v-2efd53a5",
    path: "/guide/notes/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2efd53a5").then(next)
    },
  },
  {
    name: "v-4b4ccafc",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b4ccafc").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-c3140f9c",
    path: "/interview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c3140f9c").then(next)
    },
  },
  {
    path: "/interview/index.html",
    redirect: "/interview/"
  },
  {
    name: "v-9a5e4a9a",
    path: "/interview/cssQuestion/CSS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9a5e4a9a").then(next)
    },
  },
  {
    path: "/interview/cssQuestion/CSS面试题.html",
    redirect: "/interview/cssQuestion/CSS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/cssQuestion/CSS面试题.html",
    redirect: "/interview/cssQuestion/CSS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-3029a03c",
    path: "/interview/jsArithmeticQuestion/JS%E7%AE%97%E6%B3%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3029a03c").then(next)
    },
  },
  {
    path: "/interview/jsArithmeticQuestion/JS算法题.html",
    redirect: "/interview/jsArithmeticQuestion/JS%E7%AE%97%E6%B3%95%E9%A2%98.html"
  },
  {
    path: "/interview/jsArithmeticQuestion/JS算法题.html",
    redirect: "/interview/jsArithmeticQuestion/JS%E7%AE%97%E6%B3%95%E9%A2%98.html"
  },
  {
    name: "v-daf2a5ea",
    path: "/interview/httpQuestion/Http%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-daf2a5ea").then(next)
    },
  },
  {
    path: "/interview/httpQuestion/Http面试题.html",
    redirect: "/interview/httpQuestion/Http%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/httpQuestion/Http面试题.html",
    redirect: "/interview/httpQuestion/Http%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-5742ba0b",
    path: "/interview/jsQuestion/JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5742ba0b").then(next)
    },
  },
  {
    path: "/interview/jsQuestion/JS面试题.html",
    redirect: "/interview/jsQuestion/JS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/jsQuestion/JS面试题.html",
    redirect: "/interview/jsQuestion/JS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-04ba2145",
    path: "/interview/reactQuestion/react%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04ba2145").then(next)
    },
  },
  {
    path: "/interview/reactQuestion/react高频面试题.html",
    redirect: "/interview/reactQuestion/react%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/reactQuestion/react高频面试题.html",
    redirect: "/interview/reactQuestion/react%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-4f5dc23d",
    path: "/interview/writeJsQuestion/%E6%89%8B%E5%86%99JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f5dc23d").then(next)
    },
  },
  {
    path: "/interview/writeJsQuestion/手写JS面试题.html",
    redirect: "/interview/writeJsQuestion/%E6%89%8B%E5%86%99JS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/writeJsQuestion/手写JS面试题.html",
    redirect: "/interview/writeJsQuestion/%E6%89%8B%E5%86%99JS%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-2eee7ded",
    path: "/interview/webSafeQuestion/web%E5%AE%89%E5%85%A8%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2eee7ded").then(next)
    },
  },
  {
    path: "/interview/webSafeQuestion/web安全面试题.html",
    redirect: "/interview/webSafeQuestion/web%E5%AE%89%E5%85%A8%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/interview/webSafeQuestion/web安全面试题.html",
    redirect: "/interview/webSafeQuestion/web%E5%AE%89%E5%85%A8%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]