/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "牧游blog",
  "description": "牧游带你上王者",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/css/style.css"
      }
    ],
    [
      "script",
      {
        "charset": "utf-8",
        "src": "/js/main.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f147a2d4",
      "path": "/"
    },
    {
      "title": "ONE",
      "frontmatter": {},
      "regularPath": "/guide/notes/one.html",
      "relativePath": "guide/notes/one.md",
      "key": "v-3d5ab436",
      "path": "/guide/notes/one.html"
    },
    {
      "title": "TWO",
      "frontmatter": {},
      "regularPath": "/guide/notes/two.html",
      "relativePath": "guide/notes/two.md",
      "key": "v-2efd53a5",
      "path": "/guide/notes/two.html"
    },
    {
      "title": "guide下的README",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-4b4ccafc",
      "path": "/guide/"
    },
    {
      "title": "主要是针对前端面试题的一些汇总",
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-c3140f9c",
      "path": "/interview/"
    },
    {
      "title": "Div元素水平垂直居中",
      "frontmatter": {},
      "regularPath": "/interview/cssQuestion/CSS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/cssQuestion/CSS面试题.md",
      "key": "v-9a5e4a9a",
      "path": "/interview/cssQuestion/CSS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 3,
          "title": "Div元素水平垂直居中",
          "slug": "div元素水平垂直居中"
        },
        {
          "level": 3,
          "title": "文本水平垂直居中",
          "slug": "文本水平垂直居中"
        },
        {
          "level": 3,
          "title": "visibility:hidden, opacity:0，display:none三者区别",
          "slug": "visibility-hidden-opacity-0-display-none三者区别"
        },
        {
          "level": 3,
          "title": "BFC指的是什么？",
          "slug": "bfc指的是什么"
        },
        {
          "level": 3,
          "title": "伪类、伪元素的区别？",
          "slug": "伪类、伪元素的区别"
        },
        {
          "level": 3,
          "title": "flex: 1 到底代表了什么？",
          "slug": "flex-1-到底代表了什么"
        }
      ]
    },
    {
      "title": "编写一个程序将数组扁平化去并除其中重复部分数据，最终得到一个升序且不重复的数组",
      "frontmatter": {},
      "regularPath": "/interview/jsArithmeticQuestion/JS%E7%AE%97%E6%B3%95%E9%A2%98.html",
      "relativePath": "interview/jsArithmeticQuestion/JS算法题.md",
      "key": "v-3029a03c",
      "path": "/interview/jsArithmeticQuestion/JS%E7%AE%97%E6%B3%95%E9%A2%98.html",
      "headers": [
        {
          "level": 3,
          "title": "编写一个程序将数组扁平化去并除其中重复部分数据，最终得到一个升序且不重复的数组",
          "slug": "编写一个程序将数组扁平化去并除其中重复部分数据-最终得到一个升序且不重复的数组"
        }
      ]
    },
    {
      "title": "http状态码有哪些？",
      "frontmatter": {},
      "regularPath": "/interview/httpQuestion/Http%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/httpQuestion/Http面试题.md",
      "key": "v-daf2a5ea",
      "path": "/interview/httpQuestion/Http%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 3,
          "title": "http状态码有哪些？",
          "slug": "http状态码有哪些"
        },
        {
          "level": 3,
          "title": "从输入URL到页面的加载全过程，简单的说一下？",
          "slug": "从输入url到页面的加载全过程-简单的说一下"
        },
        {
          "level": 3,
          "title": "浏览器渲染原理：",
          "slug": "浏览器渲染原理"
        },
        {
          "level": 3,
          "title": "http和https的区别?",
          "slug": "http和https的区别"
        },
        {
          "level": 3,
          "title": "GET和POST有什么区别？",
          "slug": "get和post有什么区别"
        },
        {
          "level": 3,
          "title": "TCP和UDP的区别？",
          "slug": "tcp和udp的区别"
        }
      ]
    },
    {
      "title": "JS基本数据类型 (7种)",
      "frontmatter": {},
      "regularPath": "/interview/jsQuestion/JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/jsQuestion/JS面试题.md",
      "key": "v-5742ba0b",
      "path": "/interview/jsQuestion/JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 3,
          "title": "JS基本数据类型 (7种)",
          "slug": "js基本数据类型-7种"
        },
        {
          "level": 3,
          "title": "JS引用类型 (5种)",
          "slug": "js引用类型-5种"
        },
        {
          "level": 3,
          "title": "几种判断数据类型的方法",
          "slug": "几种判断数据类型的方法"
        },
        {
          "level": 3,
          "title": "对象的深浅拷贝",
          "slug": "对象的深浅拷贝"
        },
        {
          "level": 3,
          "title": "ES6有哪些新特性",
          "slug": "es6有哪些新特性"
        },
        {
          "level": 3,
          "title": "var、let、const区别？",
          "slug": "var、let、const区别"
        },
        {
          "level": 3,
          "title": "问下JS的执行机制？",
          "slug": "问下js的执行机制"
        },
        {
          "level": 3,
          "title": "原型与原型链的理解？",
          "slug": "原型与原型链的理解"
        },
        {
          "level": 3,
          "title": "MVC与MVVM的区别？",
          "slug": "mvc与mvvm的区别"
        },
        {
          "level": 3,
          "title": "重绘与回流",
          "slug": "重绘与回流"
        },
        {
          "level": 3,
          "title": "提升页面性能的方法有哪些？",
          "slug": "提升页面性能的方法有哪些"
        },
        {
          "level": 3,
          "title": "什么是同源策略？",
          "slug": "什么是同源策略"
        },
        {
          "level": 3,
          "title": "跨域解决方案有哪些？",
          "slug": "跨域解决方案有哪些"
        },
        {
          "level": 3,
          "title": "cookie 与 session 的区别？",
          "slug": "cookie-与-session-的区别"
        },
        {
          "level": 3,
          "title": "闭包的原理？",
          "slug": "闭包的原理"
        },
        {
          "level": 3,
          "title": "JS变量提升？",
          "slug": "js变量提升"
        },
        {
          "level": 3,
          "title": "SSR服务端渲染原理？",
          "slug": "ssr服务端渲染原理"
        },
        {
          "level": 3,
          "title": "require、import区别？",
          "slug": "require、import区别"
        },
        {
          "level": 3,
          "title": "如何实现图片懒加载?",
          "slug": "如何实现图片懒加载"
        },
        {
          "level": 3,
          "title": "如何实现选中复制功能？",
          "slug": "如何实现选中复制功能"
        },
        {
          "level": 3,
          "title": "Promise 和 Async/await的区别？",
          "slug": "promise-和-async-await的区别"
        },
        {
          "level": 3,
          "title": "为什么0.1+0.2 ! == 0.3，如何让其相等？",
          "slug": "为什么0-1-0-2-0-3-如何让其相等"
        },
        {
          "level": 3,
          "title": "实现一个链式调用方法，并按照设置的等待时间依次打印出想要的结果",
          "slug": "实现一个链式调用方法-并按照设置的等待时间依次打印出想要的结果"
        },
        {
          "level": 3,
          "title": "浏览器事件循环的运行机制？",
          "slug": "浏览器事件循环的运行机制"
        },
        {
          "level": 3,
          "title": "浏览器缓存",
          "slug": "浏览器缓存"
        },
        {
          "level": 3,
          "title": "Javascript的编译原理是如何运行的？",
          "slug": "javascript的编译原理是如何运行的"
        },
        {
          "level": 3,
          "title": "介绍下 Set、Map、WeakSet 和 WeakMap 的区别？",
          "slug": "介绍下-set、map、weakset-和-weakmap-的区别"
        }
      ]
    },
    {
      "title": "react的生命周期有哪些？",
      "frontmatter": {},
      "regularPath": "/interview/reactQuestion/react%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/reactQuestion/react高频面试题.md",
      "key": "v-04ba2145",
      "path": "/interview/reactQuestion/react%E9%AB%98%E9%A2%91%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "react的生命周期有哪些？",
          "slug": "react的生命周期有哪些"
        },
        {
          "level": 3,
          "title": "react的性能优化，减少render次数？",
          "slug": "react的性能优化-减少render次数"
        },
        {
          "level": 2,
          "title": "为什么选择使用框架而不是原生?",
          "slug": "为什么选择使用框架而不是原生"
        },
        {
          "level": 2,
          "title": "虚拟DOM的优劣如何?",
          "slug": "虚拟dom的优劣如何"
        },
        {
          "level": 2,
          "title": "setState到底是异步还是同步?",
          "slug": "setstate到底是异步还是同步"
        },
        {
          "level": 2,
          "title": "React组件通信如何实现?",
          "slug": "react组件通信如何实现"
        },
        {
          "level": 2,
          "title": "React中的keys有什么作用？",
          "slug": "react中的keys有什么作用"
        },
        {
          "level": 2,
          "title": "调用 setState 之后发生了什么？",
          "slug": "调用-setstate-之后发生了什么"
        },
        {
          "level": 2,
          "title": "为什么虚拟 dom 会提高性能?（必考）",
          "slug": "为什么虚拟-dom-会提高性能-必考"
        },
        {
          "level": 2,
          "title": "react diff 原理（常考，大厂必考）",
          "slug": "react-diff-原理-常考-大厂必考"
        },
        {
          "level": 2,
          "title": "redux的工作流？",
          "slug": "redux的工作流"
        },
        {
          "level": 3,
          "title": "react fiber原理？",
          "slug": "react-fiber原理"
        },
        {
          "level": 3,
          "title": "react在16.4以后的版本为什么会移除componentWillMount、componentWillReceiveProps、componentWillUpdate这三个生命周期？",
          "slug": "react在16-4以后的版本为什么会移除componentwillmount、componentwillreceiveprops、componentwillupdate这三个生命周期"
        },
        {
          "level": 3,
          "title": "React父子组件生命周期执行顺序总结:",
          "slug": "react父子组件生命周期执行顺序总结"
        }
      ]
    },
    {
      "title": "手写call方法",
      "frontmatter": {},
      "regularPath": "/interview/writeJsQuestion/%E6%89%8B%E5%86%99JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/writeJsQuestion/手写JS面试题.md",
      "key": "v-4f5dc23d",
      "path": "/interview/writeJsQuestion/%E6%89%8B%E5%86%99JS%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 3,
          "title": "手写call方法",
          "slug": "手写call方法"
        },
        {
          "level": 3,
          "title": "手写bind方法",
          "slug": "手写bind方法"
        },
        {
          "level": 3,
          "title": "手写New方法",
          "slug": "手写new方法"
        },
        {
          "level": 3,
          "title": "手写Promise方法",
          "slug": "手写promise方法"
        },
        {
          "level": 3,
          "title": "实现一个深拷贝",
          "slug": "实现一个深拷贝"
        },
        {
          "level": 3,
          "title": "实现一个防抖函数",
          "slug": "实现一个防抖函数"
        },
        {
          "level": 3,
          "title": "ES5实现原型继承",
          "slug": "es5实现原型继承"
        },
        {
          "level": 3,
          "title": "简单手写vue双向数据绑定？",
          "slug": "简单手写vue双向数据绑定"
        }
      ]
    },
    {
      "title": "XSS攻击（跨站脚本攻击）",
      "frontmatter": {},
      "regularPath": "/interview/webSafeQuestion/web%E5%AE%89%E5%85%A8%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "interview/webSafeQuestion/web安全面试题.md",
      "key": "v-2eee7ded",
      "path": "/interview/webSafeQuestion/web%E5%AE%89%E5%85%A8%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "XSS攻击（跨站脚本攻击）",
          "slug": "xss攻击-跨站脚本攻击"
        },
        {
          "level": 2,
          "title": "CSRF攻击（跨站请求伪造）",
          "slug": "csrf攻击-跨站请求伪造"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "面试题",
        "link": "/interview/jsQuestion/JS面试题.md"
      },
      {
        "text": "懵逼指南",
        "link": "/guide/"
      },
      {
        "text": "工具箱",
        "items": [
          {
            "text": "在线编辑",
            "items": [
              {
                "text": "图片压缩",
                "link": "https://tinypng.com/"
              }
            ]
          },
          {
            "text": "在线服务",
            "items": [
              {
                "text": "阿里云",
                "link": "https://www.aliyun.com/"
              },
              {
                "text": "腾讯云",
                "link": "https://cloud.tencent.com/"
              }
            ]
          },
          {
            "text": "博客指南",
            "items": [
              {
                "text": "掘金",
                "link": "https://juejin.im/"
              },
              {
                "text": "CSDN",
                "link": "https://blog.csdn.net/"
              }
            ]
          }
        ]
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "新手指南",
          "collapsable": true,
          "children": [
            "/guide/notes/one"
          ]
        },
        {
          "title": "知码学院",
          "collapsable": true,
          "children": [
            "/guide/notes/two"
          ]
        }
      ],
      "/interview/": [
        {
          "title": "面试题汇总",
          "collapsable": true,
          "children": [
            {
              "title": "JS面试题",
              "path": "/interview/jsQuestion/JS面试题"
            },
            {
              "title": "手写JS面试题",
              "path": "/interview/writeJsQuestion/手写JS面试题"
            },
            {
              "title": "Http面试题",
              "path": "/interview/httpQuestion/Http面试题"
            },
            {
              "title": "CSS面试题",
              "path": "/interview/cssQuestion/CSS面试题"
            },
            {
              "title": "web安全面试题",
              "path": "/interview/webSafeQuestion/web安全面试题"
            },
            {
              "title": "react高频面试题",
              "path": "/interview/reactQuestion/react高频面试题"
            },
            {
              "title": "JS算法题",
              "path": "/interview/jsArithmeticQuestion/JS算法题"
            }
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "searchMaxSuggestoins": 10,
    "serviceWorker": {
      "updatePopup": {
        "message": "有新的内容.",
        "buttonText": "更新"
      }
    },
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页 ！"
  }
}